version: '3.9'
services:
  webui:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: webui-next
    volumes:
      - .:/next/webui
      - node_modules:/next/webui/node_modules
    ports:
      - 3000:3000
    tty: true
volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
